packages:
  - "packages/*"
  - "examples/*"

catalog:
  "@comunica/bindings-factory": 2.7.0
  "@comunica/query-sparql-rdfjs": ^2.10.0
  "@eslint-community/eslint-plugin-eslint-comments": ^4.3.0
  "@eslint/compat": ^1.1.1
  "@eslint/eslintrc": ^3.1.0
  "@eslint/js": ^9.7.0
  "@jest/expect": ^29.7.0
  "@jest/globals": ^29.5.0
  "@jest/types": ^29.6.3
  "@m-ld/m-ld": 0.10.1-edge.4
  "@rdfjs/types": 1.1.0
  "@testing-library/react": ^16.0.0
  "@types/eslint__eslintrc": ^2.1.1
  "@types/eslint__js": ^8.42.3
  "@types/lodash-es": ^4.17.8
  "@types/n3": ^1.16.0
  "@types/node": 20.3.1
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@types/sparqljs": ^3.1.4
  "@typescript-eslint/eslint-plugin": ^8.0.0-alpha.54
  "@typescript-eslint/parser": ^8.0.0-alpha.54
  asynciterator: ^3.9.0
  eslint: ^9.7.0
  eslint-import-resolver-typescript: npm:@peeja/eslint-import-resolver-typescript@3.6.3
  eslint-plugin-import-x: ^3.1.0
  eslint-plugin-jest-formatting: ^3.1.0
  eslint-plugin-promise: ^7.0.0
  expect: ^29.7.0
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  jsonld: 8.1.1
  jsonld-context-parser: ^2.3.0
  knip: ^5.27.0
  lodash-es: 4.17.21
  memory-level: ^1.0.0
  n3: 1.16.4
  rambdax: ^10.0.0
  rdf-data-factory: 1.1.1
  rdf-string: ^1.6.3
  react: ^18.3.1
  react-dom: ^18.3.1
  rxjs: ^7.8.1
  setimmediate: ^1.0.5
  sparqlalgebrajs: 4.2.0
  sparqljs: 3.6.2
  table: 6.8.1
  ts-jest: ^29.1.0
  ts-node: ^10.9.2
  tsup: ^8.2.3
  type-fest: 3.7.1
  typescript: ^5.5.3
